{{- if .Values.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway-llm-ops.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  infrastructure:
    parametersRef:
      group: enterpriseagentgateway.solo.io
      kind: EnterpriseAgentgatewayParameters
      name: {{ include "agentgateway-llm-ops.parametersName" . }}
  listeners:
    - name: http
      port: {{ .Values.gateway.listeners.http.port }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
